/*
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:

 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#define DEBUG argc > 1

int main(int argc, char *argv[])
{
  int fib1, fib2, nextFib, total;

  fib1 = 1;
  fib2 = 2;
  total = 2;
  
  while ( (nextFib = fib1 + fib2) < 4000000)
  {
    if ( !(nextFib & 1) ) total += nextFib;
    fib1 = fib2;
    fib2 = nextFib;
    if (DEBUG) printf("%d ", fib2);
  }

  if (DEBUG) printf("\n");
  printf("%d\n", total);

  return 0;
}
